### PR TITLE
Add GitHub action "Register Package"

### PR DESCRIPTION
**Pull request by singularitti**
This file is generated by [PkgTemplates.jl](https://invenia.github.io/PkgTemplates.jl/dev/user/#PkgTemplates.RegisterAction).
This action can make releasing a new version very easy:
image
Just click "Run Workflow", type your new version and click confirm, done! A new version will be registered on Julia's `General` registry.

### CODE REVIEW

**Comment by szcf-weiya** [comment]
Thanks for letting me know about this feature. But I think commenting with `@` is easy enough, such as here https://github.com/szcf-weiya/LaTeXTables.jl/commit/5904b083e5ba349c735da2efcde2e5f695bdf0e5#commitcomment-94972804

**Comment by singularitti** [comment]
The benefit of using it is that you do not have to change the [`version` field in `Project.toml`](https://github.com/szcf-weiya/LaTeXTables.jl/blob/5904b083e5ba349c735da2efcde2e5f695bdf0e5/Project.toml#L4), which I often forget myself. If this does not trouble you, I will close this PR.

**Comment by szcf-weiya** [comment]
Thanks for sharing your tips. Currently, it works well for me. But maybe someday I will re-consider your suggestion.

**Comment by singularitti** [comment]
Sure.

**Pull request closed without merging**
